[platformio]
default_envs = m5stickc-plus-11

[env:m5stickc-plus-11]
platform = espressif32@6.12.0
board = m5stick-c
framework = arduino
monitor_speed = 115200
monitor_filters = esp32_exception_decoder, time
build_flags =
    -DCORE_DEBUG_LEVEL=3
    -DNIMBLE_CPP_LOG_LEVEL=2
lib_deps =
    m5stack/M5StickCPlus@^0.1.0
